.gitignore, Gruntfile.js, README.md, ooiui/static/js/core/science/map.js, ooiui/templates/science/index.html, package.json
- Adds task to concatenate all the javascript modules for science UI
into one JS.
- We'll need to minify this for production's sake.
Note: d3.js won't work and will need to be explicitly sourced because
it's not strictly compliant.
=> Adds grunt-contrib-concat

ooiui/core/routes/science.py, ooiui/static/js/views/common/UserFormView.js
- Added a route for /api/user
- Removed the second this.model.save()
=> Integration for the user registration form

Gruntfile.js, ooiui/core/interface/toc.py, ooiui/templates/common/loginDemo.html, ooiui/templates/common/signup.html
- Brings back jinja template for the login
- Adds jinja template for registration
- Fixes dep in toc.py
=> Adds some consistency to the templates

Gruntfile.js, ooiui/static/js/partials/LoginForm.html, ooiui/static/js/views/common/LoginView.js, ooiui/templates/common/loginDemo.html, ooiui/templates/common/signup.html
- Adds cookie setting to the login view.
=> Adds embedded cookies to set tokens

Gruntfile.js, ooiui/core/routes/common.py, ooiui/static/js/models/common/LoginModel.js, ooiui/static/js/partials/Alert.html, ooiui/static/js/views/common/LoginView.js, ooiui/static/js/views/common/UserFormView.js, ooiui/templates/common/signup.html
- Added some messages and alerts
- Tokenized authentication
=> Tokenized Authentication

bower.json, ooiui/core/routes/science.py, ooiui/static/css/common/scienceLayout.css, ooiui/static/css/common/timeline.css, ooiui/static/js/models/common/TocColModel.js, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/common/TocColView.js, ooiui/templates/science/index_new.html
@lukecampbell as discussed here is the layout im working on. i added another route for the page so we dont step on the current version.
=> creates the new template layout for the science page

ooiui/core/routes/science.py, ooiui/static/js/models/science/ArrayModel.js, ooiui/static/js/models/science/ParameterModel.js, ooiui/static/js/models/science/PlatformDeploymentModel.js, ooiui/static/js/ooi/RelationalModel.js, ooiui/templates/science/index_new.html
- A base class that has the ability to synchronize and fetch
collections of other models with a reference key.
=> Adds OOI.RelationalModel

ooiui/static/js/partials/TOCItem.html, ooiui/static/js/views/common/TOCView.js
Just until the vocabulary can be fixed
=> Revert back to use reference designators

ooiui/core/routes/common.py, ooiui/static/js/partials/Panel.html, ooiui/templates/common/basic.html, ooiui/templates/common/chartDemo.html, ooiui/templates/science/index.html
=> Adds chart demo

requirements.txt
Found during automated deployment testing.
=> Changes numpy install to before netCDF4.

Gruntfile.js, ooiui/static/css/common/scienceLayout.css, ooiui/static/js/partials/TOCItem.html, ooiui/static/js/views/common/TOCView.js
- Now the table of contents actually displays the correct display names
=> Updates the display names in the table of contents

Gruntfile.js, ooiui/static/css/common/timeline.css, ooiui/static/js/partials/NewEvent.html, ooiui/static/js/partials/TimeLineEvent.html, ooiui/static/js/views/common/NewEventView.js, ooiui/static/js/views/common/TimeLineEventView.js, ooiui/templates/common/opLog.html
add timeline event view, dont merge yet as i want to add the switching between the two options
=> add event display in timeline view

Gruntfile.js, ooiui/core/routes/common.py, ooiui/static/js/models/common/LoginModel.js, ooiui/static/js/models/common/UserModel.js, ooiui/static/js/views/common/EventView.js, ooiui/static/js/views/common/LoginView.js, ooiui/templates/common/opLog.html
- Views should only use the jquery for elements under itself.
=> Updates the login view

ooiui/static/js/partials/Event.html
@lukecampbell merge when ready. disables the drop down
=> disable drop down

Gruntfile.js, ooiui/static/css/common/orgsidebarview.css, ooiui/static/js/partials/OrgSidebar.html, ooiui/static/js/views/common/OrgSidebarView.js, ooiui/templates/common/opLog.html
Now the org view on the left will automatically select the organization that the user belongs to.
=> Orgs are selected based on logged in user

ooiui/core/routes/science.py, ooiui/static/js/models/common/ChartModel.js, ooiui/static/js/models/science/ParameterModel.js, ooiui/static/js/views/common/ChartView.js, ooiui/static/js/views/common/ChartViews.js, ooiui/templates/common/plotsDemo.html
to services for uframe data and annotations
=> add simple support for connection 

ooiui/static/js/partials/TOCItem.html, ooiui/templates/science/index.html
@lukecampbell for info, merge when ready
=> fixes tooltips for the mouseovers

Gruntfile.js, ooiui/core/routes/common.py, ooiui/static/js/models/common/UserModel.js, ooiui/static/js/models/common/UserScopeModel.js, ooiui/static/js/partials/MenuToggle.html, ooiui/static/js/partials/Navbar.html, ooiui/static/js/partials/UserEditForm.html, ooiui/static/js/views/common/NavbarView.js, ooiui/static/js/views/common/UserEditFormView.js, ooiui/templates/common/signup.html, ooiui/templates/common/userEdit.html
- This is how I see enabling/disabling accounts.
- This is also how I see managing user scopes
=> Adds screen to edit user accounts

Gruntfile.js, ooiui/static/js/models/common/ChartModel.js, ooiui/static/js/models/common/MapModel.js, ooiui/static/js/views/common/ChartView.js, ooiui/static/js/views/common/ChartViews.js, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/common/TOCView.js, ooiui/templates/common/plotsDemo.html, ooiui/templates/science/index.html
It works, however, clicking the TOC too much messes up the event listener causing lat long issues. Note I used listen on. Maybe listenTo is the better choice.
=> TOC Click changes Map

ooiui/core/routes/common.py, ooiui/static/js/partials/TroubleTicket.html, ooiui/static/js/views/common/TroubleTicketView.js, ooiui/templates/common/troubleTicket.html
=> Hooked Trouble Tickets up to Red Mine

ooiui/static/js/partials/Navbar.html
=> Added Submit a Trouble Ticket Button

ooiui/static/js/partials/DropdownUserLoggedIn.html, ooiui/static/js/partials/Navbar.html, ooiui/static/js/views/common/NavbarView.js
=> Bug #2519: Fixes logout button on Edit Users page.

ooiui/core/routes/science.py
Bug #2526: Support for backed lockdown of uframe routes.
=> updated proxy routes to now use auth

ooiui/core/routes/science.py
=> fix ui connection to uframe data plot

ooiui/templates/common/pioneerArray.html
=> fix_landing_page-added missing div tag

ooiui/core/routes/common.py, ooiui/static/css/common/pioneerArray.css, ooiui/templates/common/infrastructure.html, ooiui/templates/common/pioneerArray.html
Built basic Infrastructure page based off of original to link new Pioneer Array page, Pioneer TOC, and OOI link in navbar.
=> Infrastructure

Gruntfile.js, ooiui/static/js/views/asset_management/InstrumentView.js, ooiui/templates/asset_management/instrument_list.html
somehow a couple css things were changed for the instrument management page
=> instrument management page rework

Gruntfile.js, bower.json, ooiui/core/routes/common.py, ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/partials/StreamDownloadForm.html, ooiui/static/js/partials/StreamTableItem.html, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/static/js/views/science/StreamTableView.js, ooiui/templates/common/depthplot.html
=> Update for profile

ooiui/static/js/models/common/TroubleTicketModel.js, ooiui/static/js/partials/TroubleTicket.html, ooiui/static/js/views/common/TroubleTicketView.js, ooiui/templates/common/troubleTicket.html
- Adds the username and assignee to the comment field
- Removes the "comment" box
=> Updates the trouble ticket view

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/partials/TOC.html, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/common/TOCView.js
=> allow for time query requests

ooiui/static/js/partials/StreamItem.html, ooiui/static/js/views/science/StreamDownloadFormView.js
Replaces it with display_name.
=> Removes reference designator from download modal.

ooiui/static/css/common/streams.css, ooiui/static/js/partials/StreamDownloadForm.html, ooiui/static/js/views/science/StreamDownloadFormView.js
Adds direct download link to bottom of stream download form.
=> R3 Download Link HotFix

ooiui/static/js/models/common/UserFormModel.js, ooiui/static/js/views/common/UserFormView.js, ooiui/templates/common/signup.html
Checks for a US phone number on the primary and secondary phone fields.
Also check to make sure they aren't starting with invalid numbers for
an individual person such as 911 or 0.
=> Adds phone number validation to new user registration

ooiui/core/routes/common.py, ooiui/core/routes/science.py, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/common/TOCView.js, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/templates/science/index.html
@DanielJMaher @benjwadams this is the ui portion of the work, right now im not passing the reference designator to the ui service but thats an easy fix when we get the back end done
=> Glider track update

ooiui/static/css/common/scienceLayout.css, ooiui/static/js/views/common/MapView.js
added lat/lon and links to data catalog, asset management page
=> update and style assets map popup content

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js
@DanielJMaher we need to leave this open till @Bobfrat does the services end. ive also begun to add options for selection of profile.
<b>DO NOT MERGE YET</b>
=> adds initial multiplot capability

ooiui/static/js/partials/SVGPlotControl.html, ooiui/templates/science/streams.html
=> Format plotting area

ooiui/static/js/models/common/TroubleTicketDropdownModel.js, ooiui/static/js/models/common/TroubleTicketModel.js, ooiui/static/js/partials/TroubleTicket.html, ooiui/static/js/views/common/TroubleTicketView.js
Adds Validation and connects to redmine API.
=> Fixes Trouble Ticket Submission

ooiui/core/routes/science.py, ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js
@DanielJMaher @Bobfrat as discussed
=> tidy up plotting and update plot button

ooiui/static/js/models/asset_management/AssetModel.js, ooiui/static/js/views/asset_management/AssetView.js
@birdage , @DanielJMaher 
Sorry for the white space trimming!
Lines changed:
AssetModel.js: 41
AssetView.js: 460
=> Fixes PUT; now returning lastModifiedTimeStamp in put body

Gruntfile.js, ooiui/static/js/models/asset_management/PlatformDeploymentModel.js, ooiui/static/js/models/science/StreamModel.js, ooiui/static/js/partials/ArrayItem.html, ooiui/static/js/partials/StreamTableItem.html, ooiui/static/js/partials/TOC.html, ooiui/static/js/partials/TOCParentItem.html, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/common/SimpleTOCView.js, ooiui/static/js/views/science/StreamTableView.js, ooiui/templates/science/index.html
@DanielJMaher updates to the ui
DONT MERGE YET, waiting on @FBRTMaka changes
=> update toc view with simple view from assets

ooiui/core/routes/science.py, ooiui/static/js/models/science/StreamModel.js, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/StreamDownloadFormView.js
A few changes that were needed to support Rutgers/Steve Gaul data inspection
=> Working to fix plotting with casandra time bounded uframe

Gruntfile.js, ooiui/static/js/partials/ModalDownload.html, ooiui/static/js/partials/ModalDownloadFail.html, ooiui/static/js/views/common/ModalDownloadFailView.js, ooiui/static/js/views/common/ModalDownloadView.js, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/templates/science/streams.html
I uses XMLHttpRequest to check if the url is valid before setting window.location.href = url.
=> adds a modal after downloading data from data catalog

ooiui/templates/asset_management/assetslist.html
=> fix for asset_management

ooiui/core/routes/science.py, ooiui/static/css/common/scienceLayout.css, ooiui/static/js/models/science/StreamModel.js, ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/partials/StreamTableItem.html, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/StreamTableView.js, ooiui/templates/science/streams.html
updates the stream page plotting
<b>Dont merge yet</b>
=> update streams page

ooiui/templates/science/index.html
=> update map plot

ooiui/static/js/partials/MenuToggle.html, ooiui/templates/common/FAQ.html, ooiui/templates/common/depthplot.html, ooiui/templates/common/glossary.html, ooiui/templates/common/signup.html, ooiui/templates/common/troubleTicket.html, ooiui/templates/common/users.html, ooiui/templates/science/streams.html
Up to you if you want to merge.
=> Hides the Toc slider button in NavBar when there is no Toc on the page.

ooiui/static/js/models/asset_management/EventModel.js, ooiui/static/js/views/asset_management/EventViewPage.js, ooiui/templates/asset_management/event.html
@DanielJMaher , @oceanzus 
Adds the calibration tab to Event page.  Not editable YET.
=> Mc add cal

Gruntfile.js, ooiui/static/js/models/common/StatusUIModel.js, ooiui/static/js/views/common/StatusUIIconView.js, ooiui/templates/common/statusUI.html
Note: 
1) I set a 5 second timeout after the collection is fetch to wait for models' attribute display_name to be updated. Then render the page.
=> New status page

Gruntfile.js, ooiui/static/js/views/common/SVGView.js
=> update date picker and css

ooiui/core/routes/c2.py, ooiui/static/js/partials/ArraySideBar.html, ooiui/static/js/partials/CommandDialog.html, ooiui/static/js/views/c2/ArraySideBarView.js, ooiui/static/js/views/c2/CommandDialogView.js, ooiui/static/js/views/c2/InstrumentView.js, ooiui/static/js/views/common/SimpleTOCView.js, ooiui/templates/c2/landing.html, ooiui/templates/science/index.html
@DanielJMaher @oceanzus 
This is working on my machine.  Best to test with Coastal Pioneer.  Click start, and it will toggle to stop.
=> C2 integration with new instruments

.gitignore, Gruntfile.js, ooiui/core/routes/common.py, ooiui/core/routes/science.py, ooiui/static/css/common/plotting.css, ooiui/static/js/models/science/FilterSelectionModel.js, ooiui/static/js/models/science/StreamModel.js, ooiui/static/js/models/science/TocArrayModel.js, ooiui/static/js/models/science/TocInstrumentsModel.js, ooiui/static/js/models/science/TocMooringsModel.js, ooiui/static/js/models/science/TocParametersModel.js, ooiui/static/js/models/science/TocPlatformsModel.js, ooiui/static/js/models/science/TocStreamsModel.js, ooiui/static/js/partials/FilterPlottingSelection.html, ooiui/static/js/partials/PlatformItem copy.html, ooiui/static/js/partials/PlottingSelection.html, ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/PlottingSelectionView.js, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
=> Plotting page update

Gruntfile.js, ooiui/static/css/common/scienceLayout.css, ooiui/static/js/models/science/TocArrayModel.js, ooiui/static/js/models/science/TocModel.js, ooiui/static/js/partials/ArrayItem.html, ooiui/static/js/partials/NestedTocItem.html, ooiui/static/js/partials/TOC.html, ooiui/static/js/views/common/TOCView.js, ooiui/templates/science/index.html
=> updates to the TOC models

ooiui/core/routes/science.py, ooiui/static/js/models/science/TocArrayModel.js, ooiui/static/js/models/science/TocInstrumentsModel.js, ooiui/static/js/models/science/TocMooringsModel.js, ooiui/static/js/models/science/TocParametersModel.js, ooiui/static/js/models/science/TocPlatformsModel.js, ooiui/static/js/models/science/TocStreamsModel.js, ooiui/static/js/partials/ArrayItem.html, ooiui/static/js/partials/FilterPlottingSelection.html, ooiui/static/js/partials/NestedTocItem.html, ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/TOCView.js, ooiui/static/js/views/science/PlottingSelectionView.js, ooiui/templates/science/index.html, ooiui/templates/science/plotting.html
fixes the plotting and the toc
requires https://github.com/asascience-open/ooi-ui-services/pull/315
=> add formatting for moorings and platforms

ooiui/static/js/partials/StreamTableItem.html, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/common/TOCView.js, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
=> fix download links

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js
@DanielJMaher you will want to modify this, particularly the SVGView.js, adding in the content you want, dont forget to initialize the tooltip content in the html file.
=> add initial tooltip selection update

bower.json, ooiui/static/js/views/common/MapView.js, ooiui/templates/science/index.html
add 3 basic wms layers, add new wms library
=> adds basic wms layers

ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/PlottingSelectionView.js, ooiui/templates/science/plotting.html
@DanielJMaher only changes dates on stream selection now
=> only update times when a stream is selected

ooiui/templates/science/streams.html
@DanielJMaher , ok Dan, time to put your thinking cap on for this change lol
=> data catalog pagination: 7 to 20 per page.

ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/PlottingSelectionView.js, ooiui/templates/science/plotting.html
=> fix profile plotting

ooiui/static/js/views/science/PlottingSelectionView.js
@DanielJMaher fixes non-unique platform names getting filtered
=> updates the selection for platform name, as platform name is not unique

ooiui/static/js/ooi.js
=> for testing, increased timout to 20 hours

ooiui/static/js/views/common/TOCView.js
@DanielJMaher @FBRTMaka @oceanzus update to fix the toc list
=> update level toc code to fix parse error on toc item

ooiui/static/js/views/common/SVGView.js
@DanielJMaher , @oceanzus 
This should fix that problem - looks like it only shows on certain browsers (safari)
=> Bug Fix: functions not created correctly.

ooiui/static/js/partials/StreamDownloadForm.html
=> fixed typo

ooiui/templates/asset_management/assetslist.html, ooiui/templates/science/index.html
@oceanzus, @DanielJMaher 
Give this a shot, I'm thinking the assets are trying to be assigned to the array containers before they are ready.
I wasn't able to reproduce the error we see on casadev, so I'm not 100% sure...but it's worth a shot.
=> create a more iterative loading of the assets

ooiui/templates/science/plotting.html
@DanielJMaher , @dlangston 
Dan L, when you make these banner title instances the constructor should be in the format:
var instance = new InstanceClass({ **key**: **value** });
=> BugFix, banner title stuff

ooiui/static/css/common/plotting.css, ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js
@DanielJMaher 
Should be ready to go with qaqc:{0/1:num} in request for plot/ plotmulti and download
Please advise if there are any issues.
Thanks
=> Add checkbox params to plotting switch and request param

ooiui/static/js/views/common/MapView.js
@DanielJMaher add deployment number and date to popup
=> update map markers to only show deployment events and markers with deployment events

ooiui/static/js/views/common/SVGView.js, ooiui/templates/science/plotting.html
@DanielJMaher, still working on a couple more items so hold off on merging please.
=> Plotting updates

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/PlottingSelectionView.js, ooiui/templates/science/plotting.html
Adds error message to plot and filters the metadata from the streams.
@birdage @DanielJMaher please review
=> Add parameter selection for specialty plots

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js
@birdage @DanielJMaher, please review/merge
@dlangston , You can work on the styling of the controls now
=> Update datetimepicker and use UTC

ooiui/core/routes/science.py, ooiui/static/js/views/common/MapView.js, ooiui/templates/science/streams.html
merge conflict fix
fixed merge conflict
fixed merge conflict
fixed merge conflict
removed consol log after rebase
=> squished commits for merging

ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/static/js/views/science/StreamTableView.js, ooiui/templates/science/plotting.html
@birdage please take a look and merge
@DanielJMaher  FYI
=> Fix download data for plotting

ooiui/static/js/models/science/SeriesModel.js, ooiui/static/js/views/science/HighChartsTimeSeriesView.js, ooiui/static/js/views/science/HighchartsView.js
min max x axis = 2 plot request
=> update ui plotting to date range

ooiui/static/css/common/leaflet/map.css, ooiui/static/js/views/common/MapView.js
updates the popups when zooming
=> zooming hides the labels on the map past a certain point

ooiui/static/js/views/common/TOCView.js, ooiui/templates/science/streams.html
@DanielJMaher , This will fix a few items from the punch list as well as collating the assets together.
=> Removes "Create Asset" button from DC page, use 8 char platform name for TOC, use display names

ooiui/static/js/partials/FilterPlottingSelection.html, ooiui/static/js/views/science/PlottingSelectionView.js
added Filter placeholder to plotting drop down, still needs filter icon if possible
added filter placeholder and icon to plotting bootstrap-select dropdown
added jquery script to add a search icon and placeholer in boostrap-select dropdowns
moved function from FilterPlottingSelection to PlottingSelectionView
=> squashed commits for merge

ooiui/static/js/views/science/HighChartsTimeSeriesView.js, ooiui/templates/science/plotting.html
ERROR MSG when requesting data
INFO for params unable to be rendered in the plot
=> add error handing

ooiui/core/routes/science.py, ooiui/static/js/models/science/StreamModel.js, ooiui/static/js/partials/StreamDownloadForm.html, ooiui/static/js/views/science/StreamDownloadFormView.js
@birdage @DanielJMaher 
This goes along with https://github.com/asascience-open/ooi-ui-services/pull/362
=> Add support for downloading provenance and annotations

ooiui/static/js/partials/SVGPlotControl.html
just one last thing that missed the merge.
=> make all buttons the same style

ooiui/static/js/partials/SVGPlotControl.html
=> Change to radio button

ooiui/static/js/views/science/HighChartsTimeSeriesView.js
=> Error checking on QAQC

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js, ooiui/templates/asset_management/assetslist.html, ooiui/templates/science/plotting.html
@Bobfrat , @birdage , Just wondering about the depth profile, in the test it's looking for two but it's set to only render one.  Compared with with Casadev and it's seems like it'll never show (since you can't choose two variables).
=> implements the new TOC to non time series plot types

ooiui/static/css/common/toc_menu.css, ooiui/templates/science/streams.html
=> fixed spacing on data catalog sidebar and search bar

Gruntfile.js, bower.json, ooiui/static/js/views/common/MapView.js, ooiui/templates/science/index.html
=> re organize the map controls and init

ooiui/static/js/views/common/SVGView.js, ooiui/templates/science/plotting.html
@birdage @FBRTMaka  please review
=> Pass in correct start and end times

ooiui/static/css/common/streams.css, ooiui/static/js/ooi.js, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/common/TOCView.js, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
@DanielJMaher , @dlangston , noticed that the TOC would jump back to the top of the page when you clicked an asset, made it dizzying when you were pretty far down the tree.
=> Fixes graphic bug in TOC on stream page

ooiui/static/js/views/science/HighChartsTimeSeriesView.js
@birdage @FBRTMaka please review/merge
=> Add another layer of error checking

ooiui/static/js/ooi.js, ooiui/static/js/views/common/TOCView.js, ooiui/templates/science/streams.html
@DanielJMaher 
So this actually causes duplication - like you saw in the screen shot.  Do you think for now it's better to have no duplication and note that we are working this out?
=> This was premature, but this needs to be addressed soon

ooiui/static/js/views/common/TOCView.js, ooiui/templates/science/index.html
@DanielJMaher , @birdage , please review when you can - there is a pretty strange bug that got introduced, but this takes care of it.
This also attempts to keep the crazy zooming on the map to a min.
=> Bug Fix: Fixes 'ul#' unrecognized syntax error in TOC

ooiui/static/js/ooi.js, ooiui/static/js/views/common/MapView.js, ooiui/templates/science/index.html, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
@DanielJMaher , @birdage 
So this allows the URL to expand the TOC on Map / Data Catalog / and Plotting, as well as enable 'click to plot' from map marker on Map page.
=> Map marker to plot link.

ooiui/static/js/views/common/MapView.js, ooiui/templates/science/index.html
@FBRTMaka or @Bobfrat review and merge pls
=> toc events open the selected item on the map

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/TOCView.js, ooiui/templates/science/index.html, ooiui/templates/science/plotting.html
@DanielJMaher , this console.log was stalling the TOC too much - by about a second.
@Bobfrat , when you get a chance can you review that code change (I'm totally tolling you right now).
@birdage , could you just verify the order of loading for the TOC still makes sense, even though the fetch is outside the TOC load chain?
=> very very slight TOC load time enhancement...very slight

ooiui/static/js/views/common/TOCView.js
@FBRTMaka 
Is this going to affect anything outside of plotting?
=> Remove time from plotting parameters

ooiui/static/js/views/common/TOCView.js
@DanielJMaher , @birdage 
This will remove those assets that have '-0000' in them.
=> Remove assets that have invalid reference designators from the TOC

ooiui/static/css/common/toc_menu.css, ooiui/static/js/partials/TOC.html, ooiui/static/js/views/common/AddAnnotationView.js, ooiui/static/js/views/common/MapView.js, ooiui/templates/science/index.html, ooiui/templates/science/plotting.html
=> Annotations on plot

ooiui/static/js/views/c2/PlatformInstrumentsView.js, ooiui/templates/c2/landing.html, ooiui/templates/common/userEdit.html
@DanielJMaher this should fix the modals on c2 and the user submit modal. I still need to fix the sizing issues.
=> fixed modal on c2 and user submit

ooiui/static/js/models/science/StreamModel.js
@DanielJMaher , @birdage , this just puts in the long display name for searching.
=> support for imporved backend search features on streams

ooiui/static/js/views/science/HighChartsTimeSeriesView.js, ooiui/static/js/views/science/HighchartsView.js
@birdage please review.
@DanielJMaher fixes high charts zoom button reset and adds legend for red QAQC points
=> Add legend entry for bad qaqc and fix zoom button

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js
@DanielJMaher FYI
@FBRTMaka please review/merge
=> Add reset time button to plots

ooiui/static/js/views/common/TOCView.js
@DanielJMaher @FBRTMaka Please review/merge
=> Organize parameter dropdowns

ooiui/static/css/common/plotting.css
=> fixed date/time dropdown overflow issue

ooiui/templates/asset_management/assetslist.html
@DanielJMaher , @oceanzus , Just going to step back on the performance tweaking and separate the TOC collection of assets and the asset list created for pagination.  I think one is clobbering the other.
=> separate collections for pagination results and TOC assets

ooiui/static/js/views/science/StreamDownloadFormView.js
=> added full breadcrumb to modal

.gitignore, Gruntfile.js, bower.json, ooiui/config/__init__.py, ooiui/config/config.yml, ooiui/core/app/__init__.py, ooiui/core/routes/aa.py, ooiui/static/css/common/backgrid_aa.css, ooiui/static/js/models/aa/AlertAckModel.js, ooiui/static/js/models/aa/AlertModel.js, ooiui/static/js/models/aa/TriggeredModel.js, ooiui/static/js/partials/AcknowledgeModalForm.html, ooiui/static/js/partials/DefinitionModalForm.html, ooiui/static/js/partials/TriggeredAlertDialog.html, ooiui/static/js/views/aa/AcknowledgeModalFormView.js, ooiui/static/js/views/aa/AlertView.js, ooiui/static/js/views/aa/DefinitionModalFormView.js, ooiui/static/js/views/aa/TriggeredView.js, ooiui/templates/aa/AlertPage.html, ooiui/templates/aa/TriggeredPage.html
Based on birdage:update_for_aa
=> Adds A&A definition creation

ooiui/static/js/views/science/StreamDownloadFormView.js
@DanielJMaher 
Download now working in Firefox, was a date issue.
Please test and advise of any issues.
Thanks
=> Download Issue Firefox

ooiui/core/routes/aa.py, ooiui/static/js/partials/DefinitionModalForm.html, ooiui/static/js/views/aa/AlertView.js, ooiui/static/js/views/aa/DefinitionModalFormView.js, ooiui/templates/aa/AlertPage.html
DO NOT MERGE YET
@oceanzus and @DanielJMaher  FYI
Update does not work as yet
=> update row selection, fire event to view row information

Gruntfile.js, ooiui/static/js/partials/AlertToggleActiveModalForm.html, ooiui/static/js/views/aa/AlertToggleActiveModalFormView.js, ooiui/static/js/views/aa/AlertView.js, ooiui/templates/aa/AlertPage.html, ooiui/templates/aa/TriggeredPage.html
=> Adds initial toggle for activating/deactivating A&A defs.

ooiui/static/js/partials/AssetEventsTable.html, ooiui/static/js/partials/StreamTableItem.html, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/StreamDownloadFormView.js
@DanielJMaher Get download data in UTC time. 
Hold off on merge and I'll fix the UTC time issue with plotting
=> Get download start/end dates in UTC

ooiui/static/js/views/aa/AcknowledgeModalFormView.js, ooiui/static/js/views/aa/AlertToggleActiveModalFormView.js, ooiui/static/js/views/aa/AlertView.js, ooiui/static/js/views/aa/TriggeredView.js, ooiui/templates/aa/AlertPage.html, ooiui/templates/aa/TriggeredPage.html
Fixes page refresh on load and after toggle.
Adds minor UI cleanup.
=> Fixes active/inactive PUT data.

ooiui/static/js/views/aa/AlertView.js, ooiui/static/js/views/aa/DefinitionModalFormView.js
* fixers parsing the stream on updating 
* remove the init render on init
* fixes severity str > int issue
@oceanzus take a look.
=> fix stream update, remove init render

ooiui/static/js/views/common/LoginView.js
@DanielJMaher 
Added method to focus username on login modal
Please check and merge
=> Login Focus

ooiui/static/js/views/asset_management/EventViewPage.js, ooiui/static/js/views/asset_management/EventsView.js, ooiui/static/js/views/common/SVGView.js, ooiui/templates/asset_management/event.html, ooiui/templates/asset_management/eventslist.html
@birdage @DanielJMaher please review/merge
=> More UTC fixes for asset events

ooiui/core/routes/common.py, ooiui/core/routes/science.py
@DanielJMaher first crack at it. Pull it down and test. This is a work in progress. As is right now, this will prevent users from going to the plotting page and asset management pages without being logged in. It will redirect to the science page
@FBRTMaka fyi
=> Permissions

ooiui/core/routes/common.py, ooiui/core/routes/science.py
Reverts asascience-open/ooi-ui#463
=> Revert "Permissions"

ooiui/static/js/partials/SVGPlotControl.html
@birdage @DanielJMaher please review/merge
=> Remove plotting depth profiles

ooiui/static/css/common/streams.css, ooiui/static/css/common/toc_menu.css, ooiui/static/js/partials/AssetEventsTable.html, ooiui/static/js/partials/StreamTable.html, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/common/TOCView.js, ooiui/static/js/views/science/StreamTableView.js, ooiui/templates/asset_management/assetslist.html, ooiui/templates/science/index.html, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
@DanielJMaher , @c0mster , @birdage , @dlangston Please review!
=> Sorting, and stuff

ooiui/static/js/models/common/TroubleTicketModel.js, ooiui/static/js/partials/TroubleTicket.html, ooiui/static/js/views/common/TroubleTicketView.js
@DanielJMaher this makes Sage the assignee and removes all the unneeded buttons.
related to https://github.com/asascience-open/ooi-ui-services/pull/386
=> Update trouble tickets

ooiui/static/css/custom/navbar.css
@DanielJMaher I have applied a fix for this testing at 1024. Let me know if we need to go smaller.
before...
after...
=> added @media to prevent map showing between banner and navbar

Gruntfile.js, ooiui/static/js/partials/ModalRedmineFail.html, ooiui/static/js/partials/ModalRedmineSuccess.html, ooiui/static/js/views/common/ModalRedmineFailView.js, ooiui/static/js/views/common/ModalRedmineSuccessView.js, ooiui/static/js/views/common/TroubleTicketView.js, ooiui/templates/common/troubleTicket.html
@DanielJMaher , @birdage please review
=> Add modals for trouble ticket success and error

ooiui/static/css/common/plotting.css
=> Fixes the A&A parameter dropdown list clipping.

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js, ooiui/templates/science/plotting.html
@DanielJMaher @birdage please review. This goes along with a services PR so merge that first.
@birdage I had to make this plot as a png because its so large as svg it was crashing my browser.
=> Add stacked time series plot

ooiui/static/js/partials/AnnotationModalForm.html, ooiui/static/js/views/common/AnnotationModalFormView.js, ooiui/templates/science/plotting.html
update to support annotation generation using user input
=> update selection of start and end date

ooiui/static/css/common/plotting.css, ooiui/static/css/custom/custom.css, ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js, ooiui/templates/science/plotting.html
@DanielJMaher I am adding the note about the plots being decimated to 1000 data points in a different branch. This was just to fix the spacing and overflow of the controls.
=> Svg control spacing fix

Gruntfile.js, ooiui/static/css/common/index.css, ooiui/static/css/common/mapLegend.css, ooiui/static/js/views/common/MapView.js
add the wms legends to the map
=> add wms legend

ooiui/static/js/views/common/TOCView.js
@FBRTMaka @DanielJMaher 
please review/merge
=> Update the url as you click on ToC

ooiui/static/js/partials/DefinitionModalForm.html, ooiui/static/js/views/aa/DefinitionModalFormView.js, ooiui/static/js/views/aa/TriggeredView.js, ooiui/templates/aa/AlertPage.html
Fixes minor bugs with column values and feedback.
=> Adds bug fixes for ticket 8397

ooiui/static/js/partials/AssetInspector.html
=> changed Meta Data to Metadata in AssetInspector.html

ooiui/static/css/common/index.css, ooiui/static/js/views/common/MapView.js
updates and add selection enabled toggling of the legends
=> update legend show/hide on selection

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/HighChartsTimeSeriesView.js, ooiui/static/js/views/science/HighchartsView.js, ooiui/templates/science/plotting.html
- add "add" button
- show and hide the add button
- create new collection and add ability to get data
- create new axis when appropriate and add the data
=> update ui to support multi station plotting

ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/partials/StatusAlertIconItem.html, ooiui/static/js/views/aa/StatusAlertIconView.js
DO NOT MERGE YET.
update to status page
=> update status page

ooiui/static/js/models/asset_management/AssetModel.js, ooiui/static/js/views/common/TOCView.js
=> improved load time in TOC and better error checking

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/TOCView.js
@dlangston , lets review this this morning when I get in over a cup of tea! :P
=> fixes TOC to correctly show all items again

ooiui/static/js/views/common/MapView.js
@DanielJMaher review and merge please
=> color glider tracks differently

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js
=> Fix add button

ooiui/static/css/common/plotting.css, ooiui/static/css/custom/custom.css, ooiui/static/js/partials/PlotEvent.html
@birdage @DanielJMaher @FBRTMaka  Fixed stylings on streaming page and lightened success button color
Question...
Should this be a Success button? Seems like it is more of an Info button sense it is a drop down to another choice. I think of Success as Login, Submit, Apply.
Bootstrap button definitions:
Standard - Standard button
Primary - Provides extra visual weight and identifies the primary action in a set of buttons
Success - Indicates a successful or positive action
Info - Contextual button for informational alert messages
Warning - Indicates caution should be taken with this action
Danger - Indicates a dangerous or potentially negative action
Link - Deemphasize a button by making it look like a link while maintaining button behavior
=> Data catalog button fix

ooiui/static/css/common/status.css, ooiui/static/js/partials/StatusAlert.html, ooiui/static/js/partials/StatusAlertIconItem.html, ooiui/static/js/views/aa/StatusAlertTableView.js, ooiui/static/js/views/asset_management/AssetMapView.js, ooiui/templates/common/status.html
@DanielJMaher based on feedback
=> tidy up status page, based on feedback

ooiui/static/js/partials/SVGPlotControl.html
@birdage @DanielJMaher this brings back the stacked time series. Ready to review/merge
=> Add stacked timeseries back to UI

ooiui/static/js/views/aa/StatusAlertTableView.js
@birdage , @DanielJMaher , handles the error thrown when searching.  Would need some more time on it if possible.
=> error handling for search extension

ooiui/static/css/common/loginDemo.css, ooiui/static/js/partials/LoginForm.html, ooiui/static/js/views/common/LoginView.js
@DanielJMaher I didn't add a Success message because the modal disappears before you can read one. I can add a pop up but that will just create one more step to logging in. Plus, once you are logged in your user name is displayed on the navbar.
=> 4240 login messages

ooiui/static/js/models/science/GliderTrackModel.js
=> adds patch to services glider tracks

ooiui/static/js/core/table/jquery.tablesorter.js, ooiui/templates/science/index.html
@birdage , @DanielJMaher This will fix that error message and the TOC from jumping around on the map page when clicking assets that have no instruments.
=> Mc table sorter cleanup

Gruntfile.js, ooiui/static/css/common/alerts_alarms.css, ooiui/static/css/common/status.css, ooiui/static/css/custom/navbar.css, ooiui/static/js/views/aa/AlertView.js, ooiui/templates/aa/AlertPage.html
@DanielJMaher @FBRTMaka @birdage 
before...
after...
=> Aa sticky header

ooiui/core/routes/science.py, ooiui/static/js/partials/AssetTableHeader.html, ooiui/static/js/views/asset_management/AssetView.js, ooiui/templates/asset_management/assetslist.html
=> add export asset link

ooiui/static/js/partials/SVGPlotControl.html
@DanielJMaher FYI
@dlangston We still need to pretty this up a bit!
=> Remove some qaqc tests

ooiui/static/js/models/common/UserModel.js, ooiui/static/js/partials/UserEditForm.html, ooiui/static/js/views/common/UserEditFormView.js, ooiui/static/js/views/common/UserFormView.js, ooiui/templates/common/signup.html, ooiui/templates/common/users.html
Adds user information download button in JSON format.
=> Adds opt-in for OOI email notices.

Gruntfile.js, ooiui/core/routes/science.py, ooiui/static/js/models/science/SeriesModel.js, ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/HighChartsTimeSeriesView.js, ooiui/static/js/views/science/HighChartsXYScatterView.js, ooiui/static/js/views/science/HighchartsXYView.js, ooiui/templates/science/plotting.html
@birdage @FBRTMaka @DanielJMaher 
Please review. Goes with https://github.com/asascience-open/ooi-ui-services/pull/404
=> Add interpolated multistream plot

ooiui/templates/common/status.html
=> adds default option/view

ooiui/core/routes/common.py, ooiui/static/js/models/asset_management/AlfrescoDocumentModel.js, ooiui/static/js/partials/AssetInspector.html, ooiui/static/js/views/asset_management/AlfrescoDocumentView.js, ooiui/static/js/views/asset_management/AssetView.js, ooiui/templates/asset_management/assetslist.html, ooiui/templates/science/streams.html
@birdage , @DanielJMaher , here's the "NOW NOW NOW" finished version.  REMEMBER THE LINKS WON'T WORK IN CHROME!!
=> Mc alfresco

ooiui/static/js/views/asset_management/AssetMapView.js, ooiui/templates/common/status.html
=> update status marker

ooiui/static/js/views/common/AnnotationModalFormView.js, ooiui/templates/science/plotting.html
=> fix update button title

ooiui/core/routes/science.py, ooiui/static/js/models/science/StreamModel.js, ooiui/static/js/partials/StreamDownloadForm.html, ooiui/static/js/views/common/ModalDownloadView.js, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
@birdage @FBRTMaka 
Please review
@DanielJMaher FYI
=> Update download to add user email 

Gruntfile.js, ooiui/core/routes/aa.py, ooiui/static/css/common/alerts_alarms.css, ooiui/static/js/models/aa/AckAllModel.js, ooiui/static/js/models/aa/AlertClearModel.js, ooiui/static/js/models/aa/ClearAllModel.js, ooiui/static/js/models/aa/TriggeredModel.js, ooiui/static/js/models/aa/UserEventNotificationModel.js, ooiui/static/js/partials/AckAllModalForm.html, ooiui/static/js/partials/AlertToggleNotificationModalForm.html, ooiui/static/js/partials/ClearAllModalForm.html, ooiui/static/js/partials/ClearModalForm.html, ooiui/static/js/partials/DefinitionModalForm.html, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/views/aa/AckAllModalFormView.js, ooiui/static/js/views/aa/AcknowledgeModalFormView.js, ooiui/static/js/views/aa/AlertToggleNotificationModalFormView.js, ooiui/static/js/views/aa/AlertView.js, ooiui/static/js/views/aa/ClearAllModalFormView.js, ooiui/static/js/views/aa/ClearModalFormView.js, ooiui/static/js/views/aa/DefinitionModalFormView.js, ooiui/static/js/views/aa/TriggeredView.js, ooiui/templates/aa/AlertPage.html, ooiui/templates/aa/TriggeredPage.html
Requires user and user_event_notification model hookups still.
DO NOT MERGE YET
=> Adds initial workflow changes to A&A.

ooiui/static/css/common/scienceLayout.css, ooiui/static/js/partials/AssetTableHeader.html, ooiui/static/js/views/asset_management/AssetView.js, ooiui/static/js/views/common/MapView.js, ooiui/templates/science/index.html
@dlangston , @DanielJMaher , Hey DanL, fixed a couple things (error on an import and the sorting was broke).  Please review this morning.
@DanielJMaher , this also solves the problem of not having streams when selecting from the popup,
=> Instrument popup width fix

ooiui/static/js/views/common/MapView.js
=> Last Minute Update

ooiui/static/js/views/common/SVGView.js, ooiui/templates/science/plotting.html
@birdage quick update to prevent users from selecting y-component first
=> Update to interpolated plot to force user to select X first

ooiui/static/js/views/common/MapView.js
Fixes on behalf of Mr. @birdage
=> fixes glider popup dialog

ooiui/templates/science/plotting.html
=> Change to https

ooiui/templates/common/troubleTicket.html
@DanielJMaher 
This was the only place that we call a css file from a remote source.  Yay!
=> Fixes CSS secure load

ooiui/static/js/views/science/StreamDownloadFormView.js
=> Send back user name with no special characters

ooiui/static/js/views/science/HighChartsTimeSeriesView.js
=> Rename timeseries legend entries

Gruntfile.js, ooiui/core/routes/science.py, ooiui/static/js/models/science/AcousticDataModel.js, ooiui/static/js/models/science/StreamModel.js, ooiui/static/js/partials/AcousticDataTable.html, ooiui/static/js/partials/AcousticDataTableItem.html, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/views/science/AcousticDataTableView.js, ooiui/templates/science/antelope_acoustic.html
@DanielJMaher @FBRTMaka @birdage 
New 'mock' page for acoustic data. Mock service located at ooi-ui-services
=> Add acoustic data download mockup

ooiui/templates/science/plotting.html
removes anything with "count" in the units, or "_timestamp" in the variable name
=> fixes the var selection

ooiui/templates/science/antelope_acoustic.html
@DanielJMaher @FBRTMaka 
This goes with https://github.com/asascience-open/ooi-ui-services/pull/421
=> Enable sorting of antelope data

ooiui/static/js/views/science/PlottingSelectionView.js, ooiui/templates/science/plotting.html
=> Worked on translating parameters to human readable text.

ooiui/static/css/common/plotting.css, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/common/TOCView.js, ooiui/static/js/views/science/StreamTableView.js, ooiui/templates/science/index.html, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
=> Glider name update

ooiui/templates/c2/missionExecutive.html, ooiui/templates/c2/missionLoad.html
=> Adds next C2 ME update based on Pete's code updates.

ooiui/templates/science/index.html
=> Potential fix for missing instruments in map popup view

ooiui/templates/science/index.html
=> this got blasted out on that merge conflict change

Gruntfile.js, ooiui/config/config.yml, ooiui/core/routes/common.py, ooiui/static/css/common/downloadModal.css, ooiui/static/js/models/common/DataSubscriptionModel.js, ooiui/static/js/partials/ModalDownload.html, ooiui/static/js/partials/StreamDownloadForm.html, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
=> Add subscriptions

ooiui/core/routes/c2.py, ooiui/static/js/views/c2/MissionTableView.js, ooiui/templates/c2/missionExecutive.html, ooiui/templates/c2/missionLoad.html
@DanielJMaher @FBRTMaka Please review.
=> Adds mission executive and load functionality.

ooiui/static/js/partials/AssetsTableRow.html
=> bug in partial

ooiui/static/js/partials/AssetInspector.html, ooiui/static/js/views/asset_management/AlfrescoDocumentView.js, ooiui/static/js/views/asset_management/AssetView.js, ooiui/templates/asset_management/assetslist.html
=> Cruise docs

ooiui/static/css/common/camera_media.css, ooiui/static/js/partials/CameraPreview.html, ooiui/static/js/views/c2/CameraPreviewView.js, ooiui/templates/science/camera_media.html
=> add camera video

Gruntfile.js, ooiui/core/routes/aa.py, ooiui/static/js/models/aa/RetireModel.js, ooiui/static/js/partials/AlertToggleRetiredModalForm.html, ooiui/static/js/views/aa/AlertToggleRetireModalFormView.js, ooiui/static/js/views/aa/AlertView.js, ooiui/templates/aa/AlertPage.html
@DanielJMaher @birdage Please review.
=> Adds retire a definition to A&A.

ooiui/static/js/views/c2/CameraPreviewView.js, ooiui/templates/science/camera_media.html
=> update key and path

ooiui/static/js/models/asset_management/EventModel.js
@DanielJMaher This is a file that got squashed, we should keep it for the Events page
=> lets keep this

ooiui/static/js/models/science/SeriesModel.js, ooiui/static/js/models/science/StreamModel.js, ooiui/static/js/views/science/HighChartsTimeSeriesView.js, ooiui/static/js/views/science/HighchartsView.js, ooiui/templates/science/plotting.html
@DanielJMaher @FBRTMaka 
Removes duplicates from the Parameters plot dropdown menu as well.
Goes with https://github.com/asascience-open/ooi-ui-services/pull/444
=> Fix axes and names/times for time series plots

ooiui/static/js/partials/StreamTableItem.html, ooiui/static/js/views/science/StreamTableView.js
Color coded the stream's end date column based on the end date. <12h = red, <24 = yellow >24 = red.
=> Color coded streams based on end date.

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js, ooiui/templates/science/plotting.html
@DanielJMaher @FBRTMaka i think we might need a fix for the default selected
=> update avaialbe params via check box

ooiui/static/css/custom/banner.css, ooiui/static/css/custom/sidebar.css, ooiui/templates/science/index.html
fixes overlapping issue on infrastructure page as well as a spacing / padding issue on home page
=> Fix layout

ooiui/static/css/common/plotControls.css, ooiui/static/css/common/streams.css, ooiui/static/js/partials/AssetCreatorModal.html, ooiui/static/js/partials/PlotEventTableItem.html, ooiui/static/js/partials/StreamDownloadForm.html, ooiui/static/js/views/asset_management/AssetView.js, ooiui/static/js/views/science/PlotEventListView.js, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/static/js/views/science/StreamTableView.js, ooiui/templates/science/streams.html
@DanielJMaher @birdage , minor fixes:
1. Cleaned up the plot control buttons (got messed up a little on some css changes)
2. Fixed the event class column on the plotting page (now shows up again)
3. Added an info button next to the subscription button (per Eoin)
=> Mc cleanup

ooiui/config/config.yml, ooiui/static/js/views/common/UserFormView.js, ooiui/templates/common/signup.html
=> Removed role from user registration page

ooiui/static/js/models/science/SeriesModel.js, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/HighChartsXYScatterView.js, ooiui/static/js/views/science/HighChartsXYView.js, ooiui/templates/science/plotting.html
@FBRTMaka @DanielJMaher 
Update to the interp plots. Goes with https://github.com/asascience-open/ooi-ui-services/pull/450
=> Update interp plot titles and labels

ooiui/static/js/views/common/UserFormView.js, ooiui/templates/common/signup.html
Reverts asascience-open/ooi-ui#603
=> Revert "Removed role from user registration page"

ooiui/static/js/views/common/UserFormView.js
=> Adds back in new words for registering a user

ooiui/core/routes/c2.py, ooiui/core/routes/decorators.py, ooiui/static/js/ooi.js, ooiui/static/js/views/common/SVGView.js
=> Mc permissions

ooiui/templates/common/users.html
@DanielJMaher Should do the trick.
=> Fixes user table download in JSON format.

ooiui/core/routes/science.py, ooiui/static/js/views/asset_management/AssetEventsView.js, ooiui/static/js/views/asset_management/AssetView.js
=> fixes permission issues with asset managements and events...again

ooiui/static/css/common/status.css, ooiui/static/js/views/aa/StatusAlertTableView.js, ooiui/static/js/views/asset_management/AssetMapView.js
=> update colors for status

ooiui/config/config.yml, ooiui/core/routes/common.py, ooiui/static/js/models/common/PageControlModels.js, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/partials/StreamDownloadForm.html, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/static/js/views/science/StreamTableView.js, ooiui/templates/science/streams.html
@DanielJMaher @FBRTMaka please review
Keep in mind once HDVideo and echograms come alive we will need to update
=> Large file formats

ooiui/static/js/views/science/StreamDownloadFormView.js
@DanielJMaher This is a small change to the download URL
=> Update path to large data format file downloads

ooiui/static/js/partials/SVGPlotControl.html, ooiui/static/js/views/common/SVGView.js, ooiui/templates/science/plotting.html
@DanielJMaher this should fix the issue. ive testing some plots and things still work
=> always refresh the param list based on selection

ooiui/static/css/common/streams.css, ooiui/static/js/partials/StreamTableItem.html, ooiui/static/js/views/science/StreamTableView.js
@DanielJMaher @Bobfrat the cursor also shows the disabled icon when mousing over
e.g http://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=not-allowed
=> disable plot button for large data formats

ooiui/core/routes/common.py, ooiui/static/css/common/loginDemo.css, ooiui/static/js/ooi.js, ooiui/static/js/partials/LoginForm.html, ooiui/static/js/views/common/LoginView.js, ooiui/templates/science/index.html
@oceanzus @DanielJMaher 
ready for review!
=> working cilogon option

ooiui/core/routes/common.py
Reverts asascience-open/ooi-ui#628
=> Revert "use a redirect form the response to a GET request, rather than a just…"

ooiui/core/routes/common.py
@oceanzus @DanielJMaher 
Please review!
=> fixes the typos and uses the url instead of the location

ooiui/static/css/common/downloadModal.css, ooiui/static/js/models/common/PageControlModels.js, ooiui/static/js/partials/StreamDownloadForm.html, ooiui/static/js/views/science/StreamDownloadFormView.js
@DanielJMaher this updates the filter list as well to remove duplicates of the large file formats.
=> Large format download modal

ooiui/core/routes/science.py
=> we're bring plotting back

ooiui/static/js/views/common/TOCView.js
Fixed assembly names to show the either the assembly, name or reference designator as a last resort. Also fixed issue with names being repeated.
=> Fixed assembly names.

ooiui/static/js/views/common/MapView.js
=> updates for showing gliders

Gruntfile.js, bower.json, ooiui/core/routes/common.py, ooiui/static/css/common/camera_media.css, ooiui/static/js/models/c2/MediaModel.js, ooiui/static/js/models/common/CamImagesModel.js, ooiui/static/js/partials/CamImageItem.html, ooiui/static/js/partials/CameraControls.html, ooiui/static/js/views/common/CamImageView.js, ooiui/static/json/media_assets.json, ooiui/templates/science/camera_media.html
@DanielJMaher as discussed, <b>do not merge yet</b>, requires services
=> add camera image page

ooiui/config/config.yml, ooiui/core/routes/common.py, ooiui/templates/asset_management/assetslist.html
@DanielJMaher , if there is no document then this will create a sentence in the alfresco tab to say as much.
=> improved error handling for alfresco

ooiui/static/js/models/common/PageControlModels.js, ooiui/static/js/views/common/PageControlViews.js
Used the engineering instruments button to show and hide the engineering assets.
=> Made use of the engineering instruments button.

ooiui/static/js/views/common/PageControlViews.js
=> engineering instruments

ooiui/templates/aa/AlertPage.html, ooiui/templates/aa/TriggeredPage.html
@DanielJMaher the toc control update on AA pages
=> Mc add toc ctrl

ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/science/HighChartsTimeSeriesView.js, ooiui/static/js/views/science/HighChartsXYScatterView.js
@DanielJMaher @FBRTMaka please review/merge. Goes along with better error handling on service end as well
https://github.com/asascience-open/ooi-ui-services/pull/476
=> Better error message display

Gruntfile.js, ooiui/core/routes/science.py, ooiui/static/css/common/streamingdata.css, ooiui/static/js/models/science/SeriesModel.js, ooiui/static/js/partials/HighChartsStreamingDataOptionsView.html, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/common/TOCView.js, ooiui/static/js/views/science/HighChartsStreamingDataView.js, ooiui/templates/science/index.html, ooiui/templates/science/streaming_data.html
adds a streaming data page and streaming data plot...
@DanielJMaher @FBRTMaka @Bobfrat 
TODO (High -> Low)
=> initial commit for streaming data

Gruntfile.js, ooiui/core/routes/science.py, ooiui/static/css/common/streamingdata.css, ooiui/static/js/models/science/SeriesModel.js, ooiui/static/js/partials/HighChartsStreamingDataOptionsView.html, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/views/common/BannerView.js, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/common/TOCView.js, ooiui/static/js/views/science/HighChartsStreamingDataView.js, ooiui/templates/science/index.html, ooiui/templates/science/streaming_data.html
=> Add streaming data

Gruntfile.js
@oceanzus @DanielJMaher @FBRTMaka
=> fix case issue

ooiui/core/routes/common.py, ooiui/static/js/models/common/UserModel.js, ooiui/static/js/partials/UserEditForm.html, ooiui/static/js/views/common/UserEditFormView.js, ooiui/static/js/views/common/UserFormView.js, ooiui/static/js/views/common/UserTableView.js, ooiui/templates/common/signup.html
Reverts asascience-open/ooi-ui#658
=> Revert "User registration fields update"

ooiui/core/routes/common.py, ooiui/static/js/models/common/UserModel.js, ooiui/static/js/partials/DropdownUserLoggedOut.html, ooiui/static/js/partials/UserEditForm.html, ooiui/static/js/views/common/UserEditFormView.js, ooiui/static/js/views/common/UserFormView.js, ooiui/static/js/views/common/UserTableView.js, ooiui/templates/common/signup.html
@DanielJMaher @FBRTMaka Please review and test that this worked okay.
=> Saves user registration updates from the revert

Gruntfile.js, ooiui/core/routes/science.py, ooiui/static/css/common/downloadModal.css, ooiui/static/js/models/science/LargeDataFormatModel.js, ooiui/static/js/partials/LargeFormatDataTable.html, ooiui/static/js/partials/LargeFormatDataTableItem.html, ooiui/static/js/partials/StreamDownloadForm.html, ooiui/static/js/views/science/LargeDataTableView.js, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
@DanielJMaher @FBRTMaka 
New download page for large format data. Please review, pull down and test. Goes along with this services PR https://github.com/asascience-open/ooi-ui-services/pull/486
=> Large format data

ooiui/static/css/common/plotControls.css, ooiui/static/js/partials/SVGPlotControl.html
@Bobfrat @DanielJMaher fixes tooltips for plot types
=> fix tooltips for plotting types

ooiui/static/js/models/common/UserFormModel.js, ooiui/static/js/models/common/UserModel.js, ooiui/static/js/partials/UserEditForm.html, ooiui/static/js/views/common/UserTableView.js, ooiui/templates/common/signup.html, ooiui/templates/common/users.html
organization_id defaults to 9 (Other)
organization_id still persisted
New users only see "Organization" free form text field which is bound to "Other" (id=9)
=> Obfuscates organization on purpose.

ooiui/static/js/models/common/PageControlModels.js, ooiui/templates/science/index.html, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
@DanielJMaher As a Oceanographic Engineer, could you review the scientific concepts here and ensure they are all in their correct categories and names are appropriately assigned?
=> allows OR searching on scientific concepts

ooiui/static/js/models/common/PageControlModels.js
@FBRTMaka Did i make a mistake here?
=> fixes vocab per Vardaro's input

ooiui/static/js/views/common/BannerView.js
Fixes the camera timing being off by an our.  @BobFrat @oceanzus
=> Fixes Banner Timing

Gruntfile.js, ooiui/static/css/common/gliderQuickView.css, ooiui/static/js/models/science/GliderTrackModel.js, ooiui/static/js/partials/GliderQuickItemView.html, ooiui/static/js/partials/GliderQuickView.html, ooiui/static/js/views/common/MapView.js, ooiui/static/js/views/science/GliderQuickView.js, ooiui/templates/science/index.html
Do not merge....not ready yet initial PR
@DanielJMaher FYI
TODO
=> add initial glider overlay panel

ooiui/static/js/partials/DropdownUserLoggedIn.html, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/views/common/NavbarView.js
Checks for the users scopes in the navbar and only shows ui that is available to them.
=> Check for scopes in dropdown.

ooiui/static/js/views/science/HighChartsStreamingDataView.js
@DanielJMaher let me know what you want to do about this PR. and if you want me to push it up to the server.
=> Ui streaming data update

ooiui/core/routes/c2.py, ooiui/core/routes/common.py, ooiui/static/css/common/c2.css, ooiui/static/js/partials/CommandDialog.html, ooiui/static/js/views/c2/ArrayPlatformsView.js, ooiui/static/js/views/c2/CommandDialogView.js, ooiui/static/js/views/c2/PlatformInstrumentsView.js
Debug purposefully left in for now to aid c2 testing/debugging.
=> Updates C2

ooiui/static/js/views/home/array_content/array_content.js, ooiui/static/js/views/home/vector_map/vector_map.js
=> Changes zoom levels for improved views of arrays

ooiui/static/js/views/science/StreamDownloadFormView.js
There is still some front end work to paginate properly, but this is 90% there.
=> Fixes High BW Downloads.

ooiui/static/js/views/science/StreamDownloadFormView.js
Reverts asascience-open/ooi-ui#689
=> Revert "Fixes High BW Downloads."

ooiui/templates/asset_management/asset_management.html
@maka-io @DanielJMaher Please review and merge
=> Updates event subgrids.

ooiui/config/config.yml, ooiui/core/routes/aa.py, ooiui/core/routes/c2.py, ooiui/core/routes/common.py, ooiui/core/routes/science.py, ooiui/templates/common/base.html
=> Adds Pageviews for Google Analytics

Gruntfile.js, ooiui/static/css/common/scienceLayout.css, ooiui/static/js/partials/TermsDialog.html, ooiui/static/js/views/common/TermsDialogView.js, ooiui/static/js/views/common/UserFormView.js, ooiui/templates/common/signup.html, ooiui/templates/science/index.html
@DanielJMaher @oceanzus user registration terms and conditions. are there any other locations when the terms are opened from? could only see one.
=> update terms and conditions for user signup

ooiui/static/css/common/downloadModal.css, ooiui/static/js/partials/StreamDownloadForm.html, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/templates/science/data_catalog.html
=> Adds Raw Data.  Fixes High BW.  Need Pagination

ooiui/static/js/models/asset_management/PlatformModel.js, ooiui/static/js/models/science/ArrayModel.js, ooiui/static/js/views/home/array_content/array_content.js, ooiui/static/js/views/home/tile_map/tile_map.js, ooiui/static/js/views/home/vector_map/vector_map.js
@DanielJMaher @oceanzus this will take care of the problem where the TOC is still using toJSON() and the previous code stomped all over that.
=> actial toGeoJSON method instead of toJSON override

ooiui/static/css/common/plot.css, ooiui/static/js/models/science/SeriesModel.js, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/partials/science/plot/PlotControls.html, ooiui/static/js/partials/science/plot/PlotInstrumentControlItem.html, ooiui/static/js/partials/science/plot/PlotInstrumentParameterControl.html, ooiui/static/js/views/data_catalog/search_sidebar/components/FilterInput.js, ooiui/static/js/views/science/plot/BasePlot.js, ooiui/static/js/views/science/plot/ImagePlotView.js, ooiui/static/js/views/science/plot/PlotControlView.js, ooiui/static/js/views/science/plot/PlotView.js, ooiui/static/js/views/science/plot/XYPlotView.js, ooiui/templates/science/plot.html
@oceanzus just getting this on the board. adds the filter capability in, also updates the inputs. i still need to tweak the dropdown inputs in the am.
=> update plot inputs and fix filtering

ooiui/core/routes/common.py, ooiui/static/js/partials/ArrayItem.html, ooiui/static/js/partials/data_catalog/search_sidebar/components/filters/asset_filters/ArrayFilter.html, ooiui/static/js/views/science/StreamDownloadFormView.js
@DanielJMaher Very important to get TOC working.  Please merge ASAP.
=> Gets TOC working again.

ooiui/core/routes/science.py, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/partials/Navbar.html, ooiui/static/js/views/common/NavbarView.js
=> Fixes Permission Mapping

ooiui/static/css/common/plot.css, ooiui/static/js/models/science/PlotControlModel.js, ooiui/static/js/partials/science/plot/PlotControls.html, ooiui/static/js/views/science/HighChartsTimeSeriesView.js, ooiui/static/js/views/science/plot/ImagePlotView.js, ooiui/static/js/views/science/plot/PlotControlView.js, ooiui/static/js/views/science/plot/PlotView.js, ooiui/static/js/views/science/plot/XYPlotView.js
@DanielJMaher @oceanzus 
Top two images show the same data from two different tests. shows passing data in the first image.
>poly test
> all test
>multi parameter
=> add qaqc, fix message titles

ooiui/core/routes/common.py, ooiui/core/routes/science.py, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/partials/Navbar.html, ooiui/static/js/views/common/NavbarView.js
@oceanzus I checked for intended functionality.  seems to be good.
=> Removes TOC Slider unless needed

ooiui/static/js/views/science/plot/PlotView.js, ooiui/static/js/views/science/plot/XYPlotView.js, ooiui/templates/science/plot.html
@oceanzus @DanielJMaher updates
=> update default plots for vertical and fix plot band reference axis issue

ooiui/templates/science/plot.html
=> fix a weird bug related to highcharts rendering

ooiui/static/js/views/science/plot/PlotView.js
=> fix undefined issue

ooiui/templates/asset_management/asset_management.html, ooiui/templates/science/data_catalog.html
Updates navigation behavior of asset management.
Fixes time slider filter.
Modifies global search behavior.
=> Updates filter and navigation behavior of data catalog.

ooiui/templates/common/signup.html
@oceanzus Fixes issue with being unable to register
=> removes undeeded navbar and side bar

ooiui/static/js/models/asset_management/PlatformModel.js
Stolen from @maka-io 
Merge and push to uFrame @oceanzus when you are comfortable with this.
=> Fixes Cabled Array not showing

ooiui/static/css/common/data_catalog.css, ooiui/static/js/partials/data_catalog/search_sidebar/components/filters/RangeFilters.html, ooiui/static/js/views/common/UserEditFormView.js, ooiui/templates/science/data_catalog.html
Updates user profile post-editing navigation behavior.
=> Data catalog engineering filter fixes.

ooiui/config/config.yml, ooiui/core/routes/common.py, ooiui/static/css/common/data_catalog.css, ooiui/templates/common/home.html, ooiui/templates/science/data_catalog.html, ooiui/templates/science/streaming_data.html
Fixes CILogon token expire time.
Adds option to send password reset emails using local/trusted server.
=> Updates data catalog filter options.

ooiui/core/routes/c2.py, ooiui/static/js/partials/CommandDialog.html, ooiui/static/js/partials/Navbar.html, ooiui/static/js/views/common/NavbarView.js, ooiui/templates/science/data_catalog.html
Removes unneeded c2 socket.io references.
=> Adds navbar search to data catalog.

ooiui/static/css/home/array_content/array_content.css, ooiui/static/js/partials/home/array_content/ArrayContentSummaryItem.html, ooiui/static/js/views/home/array_content/array_content.js, ooiui/static/js/views/home/vector_map/vector_map.js, ooiui/templates/common/home.html
=> update page style

ooiui/static/js/partials/science/plot/PlotInstrumentParameterControl.html, ooiui/static/js/views/science/plot/PlotControlView.js, ooiui/templates/science/plot.html
@DanielJMaher we will most likely want to talk about this, as i had to make a small change to the plotting page.
=> fixes and adds additional parameters

ooiui/core/routes/decorators.py, ooiui/core/routes/science.py, ooiui/static/js/views/c2/CommandDialogView.js, ooiui/templates/common/help_access.html, ooiui/templates/common/help_login.html, ooiui/templates/science/data_catalog.html
401 error handling
DC button state based on login
c2 updates
=> Various commits

ooiui/static/css/custom/banner.css, ooiui/static/js/partials/Banner.html, ooiui/static/js/views/common/BannerView.js
@DanielJMaher fixes the terms and conditions for the news banner.
>eg not enabled
>eg enabled
=> fix terms and conditions for news banner

ooiui/templates/common/help_login.html
https://uframe-cm.ooi.rutgers.edu/issues/10546
=> Changes login 401 verbage.

ooiui/core/routes/science.py, ooiui/static/css/common/plot.css, ooiui/static/css/data_catalog/data_catalog.css, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/partials/Navbar.html, ooiui/static/js/partials/data_catalog/search_sidebar/components/filters/RangeFilters.html, ooiui/static/js/views/common/NavbarView.js, ooiui/static/js/views/science/plot/PlotInstrumentView.js, ooiui/templates/science/data_access.html
=> Adds various fixes to address data access tickets.

Gruntfile.js, ooiui/static/css/common/opLog.css, ooiui/static/css/custom/banner.css, ooiui/static/css/custom/navbar.css, ooiui/static/css/home/home.css, ooiui/static/js/partials/Banner.html, ooiui/static/js/views/common/BannerView.js, ooiui/static/js/views/common/NavbarView.js, ooiui/templates/aa/AlertPage.html, ooiui/templates/aa/CreateAlert.html, ooiui/templates/aa/TriggeredPage.html, ooiui/templates/admin/dataAdmin.html, ooiui/templates/admin/sysAdmin.html, ooiui/templates/asset_management/asset_management.html, ooiui/templates/common/FAQ.html, ooiui/templates/common/glossary.html, ooiui/templates/common/help.html, ooiui/templates/common/help_access.html, ooiui/templates/common/home.html, ooiui/templates/common/opLog.html, ooiui/templates/common/userEdit.html, ooiui/templates/common/users.html, ooiui/templates/science/camera_media.html, ooiui/templates/science/data_catalog.html, ooiui/templates/science/plot.html, ooiui/templates/science/streaming_data.html
@DanielJMaher review and test, make sure the pages work that we are delivering.
=> Fix banner css style

ooiui/static/js/partials/science/plot/PlotInstrumentParameterControl.html, ooiui/static/js/views/common/NavbarView.js, ooiui/templates/aa/AlertPage.html, ooiui/templates/aa/CreateAlert.html, ooiui/templates/aa/TriggeredPage.html, ooiui/templates/admin/dataAdmin.html, ooiui/templates/admin/sysAdmin.html, ooiui/templates/asset_management/asset_management.html, ooiui/templates/common/FAQ.html, ooiui/templates/common/glossary.html, ooiui/templates/common/help.html, ooiui/templates/common/help_access.html, ooiui/templates/common/home.html, ooiui/templates/common/opLog.html, ooiui/templates/common/userEdit.html, ooiui/templates/common/users.html, ooiui/templates/science/camera_media.html, ooiui/templates/science/data_catalog.html, ooiui/templates/science/plot.html, ooiui/templates/science/streaming_data.html
Removes duplicate units from drop-down menu.
=> Fixes page load race condition looking for banner view.

ooiui/static/js/views/home/array_content/array_content.js, ooiui/static/js/views/home/tile_map/tile_map.js, ooiui/static/js/views/home/vector_map/vector_map.js, ooiui/static/js/views/platforms/tile_map/tile_map.js
=> removes squashing of the mapzoom events

ooiui/templates/common/home.html
=> scoped the banner to the page so various views can access it

ooiui/static/js/partials/GenericPlatForm.html
=> Adds popup for platform images.  Fixes some images.

ooiui/static/css/home/array_content/array_content.css, ooiui/static/css/home/home.css, ooiui/static/js/partials/home/array_content/ArrayContentSummaryItem.html, ooiui/static/js/views/home/tile_map/tile_map.js
@oceanzus Should be pretty safe, just changed some styling issues.
=> Map icon colors

ooiui/static/js/views/platforms/tile_map/tile_map.js
=> Removes Gliders from maps

ooiui/static/css/home/home.css, ooiui/static/js/views/home/array_content/array_content.js, ooiui/static/js/views/home/tile_map/tile_map.js
@oceanzus This should allow you to highlight an array on the map and have it highlight on the left.  and vice versa.
@maka-io @birdage please review as well.
=> ALlwos for highliting between left and right of home page

ooiui/static/js/partials/home/array_content/ArrayContentSummaryItem.html
@oceanzus Fixes hovering over chevron problem
=> Missed line for highlighting.

ooiui/static/js/views/platforms/tile_map/tile_map.js
Slefmerging.. this is a simple one.
=> Reset Zoom Value

ooiui/static/js/views/platforms/tile_map/tile_map.js
Reverts asascience-open/ooi-ui#775
=> Revert "Reset Zoom Value"

ooiui/static/css/common/platform.css, ooiui/static/js/models/asset_management/PlatformModel.js, ooiui/static/js/views/platforms/tile_map/tile_map.js
Reverts asascience-open/ooi-ui#774
=> Revert "Fixes Platform Map and Lng/Lat mix up"

ooiui/static/css/common/platform.css, ooiui/static/js/models/asset_management/PlatformModel.js, ooiui/static/js/views/platforms/tile_map/tile_map.js
=> Ui fix vardaro

ooiui/static/js/models/science/PlotControlModel.js, ooiui/static/js/partials/science/plot/PlotInstrumentParameterControl.html, ooiui/static/js/views/science/plot/PlotControlView.js
@DanielJMaher goes along with https://github.com/asascience-open/ooi-ui-services/pull/519
=> Keep color checked on and disabled always

ooiui/static/css/data_catalog/search_sidebar.css
@oceanzus QOL update per user feedback.
=> Seperates Scrolling of sidebar and main section of data access

ooiui/core/routes/m2m.py, ooiui/static/js/models/common/UserModel.js, ooiui/static/js/partials/UserEditForm.html, ooiui/static/js/views/common/UserEditFormView.js, ooiui/static/js/views/common/UserFormView.js, ooiui/templates/science/data_access.html
Adds user-who-changed scope and API token logging to log file.
=> Adds M2M API token and 'bad' stream filtering.

ooiui/templates/science/data_access.html
=> Fixes data download button issue.

ooiui/static/js/models/asset_management/PlatformModel.js
=> Fixes North South Flip

ooiui/static/js/views/home/tile_map/tile_map.js
=> Removes Mobile Assets from Main Map

Gruntfile.js, ooiui/static/css/common/patchNotes.css, ooiui/static/js/models/common/uFramePatchNotes.js, ooiui/static/js/models/common/uiPatchNotes.js, ooiui/static/js/partials/PatchNotes.html, ooiui/static/js/views/common/PatchNotes.js, ooiui/static/json/uFramePatchNotes.json, ooiui/static/json/uiPatchNotes.json, ooiui/templates/common/help.html
@oceanzus Patch Notes added to Help page.
=> Adds page for displaying UI and uFrame Patch Notes

ooiui/static/json/uFramePatchNotes.json
Created from build Jenkins Deployment #146 and #147 feeding Jenkins Nightly Package #142
Do not merge yet.  Changes incoming.  Just creating this to help Bart.
=> uFrame Release Notes Version uframe_ooi_20161027_f6f2d988a971370b0504652023e7e3b90e5ad651

ooiui/static/css/common/patchNotes.css, ooiui/static/json/uFramePatchNotes.json, ooiui/static/json/uiPatchNotes.json
=> Patch notes 1 1 0

ooiui/templates/science/data_access.html
@DanielJMaher This is a critical fix that need to be merged.  Solves hang in Data Access page when logged in.  Also removes repetitive /api/current_user calls.
=> Fixes bug in user-scope-defined button link creation.

ooiui/templates/science/data_access.html
@DanielJMaher Fixes my mistake from the status PR.
=> Uncommented download modal trigger code.

ooiui/static/js/views/common/ModalDownloadView.js, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/templates/science/data_access.html, ooiui/templates/science/data_catalog.html, ooiui/templates/science/plot.html, ooiui/templates/science/plotting.html, ooiui/templates/science/streams.html
@DanielJMaher this goes into the redesign branch right?
=> Add time to completion to download success modal

ooiui/static/js/views/science/plot/XYPlotView.js
@DanielJMaher Also removes the seconds since 1900 axis label when plotting time.
=> Multiple series for spectral irradiance plots

ooiui/static/json/uFramePatchNotes.json
Also reformatted previous version numbering.
=> uFrame Version update

ooiui/static/json/uFramePatchNotes.json
=> json format fix

ooiui/static/js/partials/PatchNotes.html, ooiui/static/js/views/common/PatchNotes.js, ooiui/static/json/uFramePatchNotes.json, ooiui/static/json/uiPatchNotes.json
Adds UI and uframe release note dates.
=> Adds date version was tagged to json format.

ooiui/static/json/uFramePatchNotes.json
- added uframe 1.2.5 notes
- fixed whitespace formatting for previous versions
=> added uframe 1.2.5 release notes

ooiui/core/routes/m2m.py, ooiui/static/css/custom/custom.css, ooiui/static/js/partials/AnnotationModalForm.html, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/partials/Navbar.html, ooiui/static/js/views/common/AnnotationModalFormView.js, ooiui/static/json/uiPatchNotes.json, ooiui/templates/common/help_m2m.html, ooiui/templates/science/data_access.html
=> Fixes annotation times for updated constraints

bower.json, ooiui/core/routes/common.py, ooiui/core/routes/m2m.py, ooiui/core/routes/science.py, ooiui/static/css/custom/custom.css, ooiui/static/js/models/asset_management/SiteStatusModel.js, ooiui/static/js/models/common/AnnotationModel.js, ooiui/static/js/models/science/PlotControlModel.js, ooiui/static/js/models/science/SeriesModel.js, ooiui/static/js/partials/AnnotationModalForm.html, ooiui/static/js/partials/AnnotationTableItem.html, ooiui/static/js/partials/GenericPlatFormStatus.html, ooiui/static/js/partials/GenericPlatFormStatusTable.html, ooiui/static/js/partials/LoggedInNavItems.html, ooiui/static/js/partials/home/array_content/ArrayContentSummaryItem.html, ooiui/static/js/partials/science/plot/PlotControls.html, ooiui/static/js/views/c2/PlatformStatusView.js, ooiui/static/js/views/common/AnnotationModalFormView.js, ooiui/static/js/views/common/TimelineItemView.js, ooiui/static/js/views/home/array_content/array_content.js, ooiui/static/js/views/home/vector_map/vector_map.js, ooiui/static/js/views/platforms/GenericPlatFormStatusView.js, ooiui/static/js/views/science/AnnotationTableView.js, ooiui/static/js/views/science/plot/PlotControlView.js, ooiui/static/js/views/science/plot/PlotView.js, ooiui/static/json/uiPatchNotes.json, ooiui/templates/common/svgplot.html, ooiui/templates/science/data_access.html, ooiui/templates/science/index.html
=> Sprint 9 Release

ooiui/core/routes/common.py, ooiui/static/js/models/common/uFramePatchNotes.js, ooiui/static/json/uFramePatchNotes.json, ooiui/static/json/uiPatchNotes.json, ooiui/templates/common/help.html
=> Adds sprint 10 updates.

ooiui/static/js/partials/science/plot/PlotControls.html, ooiui/static/json/uiPatchNotes.json
=> Fixes missing Plot Types due to bug in 13254. (13280)

ooiui/static/js/views/common/ModalDownloadView.js, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/templates/science/data_access.html
=> Adds time and size estimate into download confirmation dialog.

ooiui/static/js/models/science/StreamModel.js, ooiui/static/js/partials/science/plot/PlotInstrumentControlItem.html, ooiui/static/js/partials/science/plot/PlotInstruments.html, ooiui/static/js/partials/science/plot/PlotInstrumentsItem.html, ooiui/static/js/views/science/AnnotationTableView.js, ooiui/static/json/uiPatchNotes.json, ooiui/templates/science/data_access.html
=> Sprint 13 Hotfix #3

ooiui/core/routes/science.py, ooiui/static/js/models/science/StreamModel.js, ooiui/static/js/views/science/StreamDownloadFormView.js, ooiui/static/json/uiPatchNotes.json
=> Fixes time and size estimator launching erroneous download attempts.

ooiui/core/routes/common.py, ooiui/static/css/common/plot.css, ooiui/static/css/custom/banner.css, ooiui/static/js/models/admin/SystemAdminModel.js, ooiui/static/js/partials/DropdownUserLoggedIn.html, ooiui/static/js/partials/NewsBanner.html, ooiui/static/js/views/admin/SystemAdminView.js, ooiui/static/js/views/common/BannerView.js, ooiui/static/js/views/common/ModalDialogView.js, ooiui/static/js/views/science/plot/PlotControlView.js, ooiui/templates/common/home.html, ooiui/templates/science/data_access.html, requirements.txt
Addresses tickets:
Reset plot (10554)
Six parameters in plot view. (10550)
Removes operator log menu item. (11372)
Addresses security issue. (14492)
=> Adds metadata banner to main site.

ooiui/static/js/partials/Navbar.html, ooiui/static/js/views/common/CamImageView.js, ooiui/static/js/views/common/SVGView.js, ooiui/static/js/views/home/array_content/array_content.js, ooiui/static/js/views/science/plot/ImagePlotView.js, ooiui/static/js/views/science/plot/PlotControlView.js, ooiui/static/json/uiPatchNotes.json, ooiui/templates/science/camera_media.html, ooiui/templates/science/data_access.html
=> Various updates for v1.8.2.

ooiui/static/js/partials/data_catalog/search_sidebar/components/filters/asset_filters/InstrumentFilter.html, ooiui/static/js/partials/data_catalog/search_sidebar/components/filters/asset_filters/PlatformFilter.html, ooiui/static/json/uiPatchNotes.json, ooiui/templates/common/statusTree.html, ooiui/templates/science/camera_media.html
Data Catalog: Fixes platform and instrument filters. (14742)
Data Catalog: Changes parameter standard name to contents of netcdf_name. (14737)
Media: Fixes broken elemental reference. (14757)
=> Version 1.9.1

ooiui/static/js/partials/UserEditForm.html, ooiui/static/js/views/common/UserEditFormView.js, ooiui/static/json/uiPatchNotes.json
=> Updates scope rendering. (14783)
